import { ScoredTopic } from './editorialScoringService.js';
import { NewsItem, Category } from '../models/types.js';
import { addNewsItem } from './newsService.js';
import { logger } from '../utils/logger.js';

export class AIContentGenService {
  public async generatePulseArticle(topic: ScoredTopic): Promise<NewsItem> {
    logger.autonomous('ContentGenerator', `Synthesizing article generation for topic: "${topic.topic}"`);

    await new Promise(res => setTimeout(res, 600));

    const newArticle: Omit<NewsItem, 'id' | 'publishedAt' | 'upvotes'> = {
      title: topic.topic,
      summary: `Autonomous breakdown on ${topic.topic.toLowerCase()}. Analyzed across ${topic.sourceVolume} web citations with +${topic.velocityGrowth} acceleration.`,
      content: `Recent breakthroughs in ${topic.category.toLowerCase()} demonstrate that ${topic.topic.toLowerCase()} is rapidly reshaping developer workflows and enterprise infrastructure. Industry benchmarks indicate widespread adoption across key technology sectors.`,
      category: (topic.category as Category) || 'LLMs',
      author: 'TechPulse Autonomous Engine',
      source: 'Autonomous AI Creator',
      url: 'https://techpulse.ai/autogen',
      readTime: '4 min read',
      sentiment: 'Bullish',
      impactScore: topic.editorialScore,
      aiGenerated: true,
      tags: [...topic.keywords, 'Autogenerated', 'AI-Pulse']
    };

    const created = addNewsItem(newArticle);
    logger.autonomous('ContentGenerator', `Successfully generated and published news pulse: ID ${created.id}`);
    return created;
  }
}

export const aiContentGenService = new AIContentGenService();
